services:
  agd_database:
    image: mysql:5.7
    command: --max_allowed_packet=30M
    restart: always
    environment:
      MYSQL_DATABASE: 'hospitalizacion'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/T1.3.2.Creacion_Tablas.sql:/docker-entrypoint-initdb.d/2.sql
      - ./scripts/T1.3.3.Insertar_Datos.sql:/docker-entrypoint-initdb.d/3.sql
